export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#111319",
        "surface": "#111319",
        "surface-dim": "#111319",
        "surface-bright": "#373940",
        "surface-container-lowest": "#0c0e14",
        "surface-container-low": "#191b22",
        "surface-container": "#1d1f26",
        "surface-container-high": "#282a30",
        "surface-container-highest": "#33343b",
        "surface-variant": "#33343b",
        "surface-tint": "#f9bc45",
        "on-surface": "#e2e2ea",
        "on-surface-variant": "#d4c4af",
        "on-background": "#e2e2ea",
        "inverse-surface": "#e2e2ea",
        "inverse-on-surface": "#2e3037",
        "outline": "#9c8f7b",
        "outline-variant": "#504535",
        "primary": "#ffda9c",
        "primary-container": "#f5b942",
        "primary-fixed": "#ffdea8",
        "primary-fixed-dim": "#f9bc45",
        "on-primary": "#422d00",
        "on-primary-container": "#6a4a00",
        "on-primary-fixed": "#271900",
        "on-primary-fixed-variant": "#5e4200",
        "inverse-primary": "#7c5800",
        "secondary": "#bec7db",
        "secondary-container": "#40495a",
        "secondary-fixed": "#dae3f7",
        "secondary-fixed-dim": "#bec7db",
        "on-secondary": "#283140",
        "on-secondary-container": "#b0b9cc",
        "on-secondary-fixed": "#131c2a",
        "on-secondary-fixed-variant": "#3e4757",
        "tertiary": "#66fa8c",
        "tertiary-container": "#45dd73",
        "tertiary-fixed": "#6bff8f",
        "tertiary-fixed-dim": "#4ae176",
        "on-tertiary": "#003915",
        "on-tertiary-container": "#005d27",
        "on-tertiary-fixed": "#002109",
        "on-tertiary-fixed-variant": "#005321",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        // Custom brand colors
        "void": "#12141A",
        "investigation": "#1B2433",
        "amber-accent": "#F5B942",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "base": "4px",
        "xs": "8px",
        "sm": "12px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "grid-gutter": "20px",
        "grid-margin": "24px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      backgroundImage: {
        'grid-pattern': 'linear-gradient(to right, rgba(255,255,255,0.05) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.05) 1px, transparent 1px)',
      },
    },
  },
  plugins: [],
}
